-- WHERE 조건 및 비교
SELECT * FROM EMPLOYEES;
SELECT * FROM EMPLOYEES WHERE JOB_ID = "IT_PROG";

SELECT FIRST_NAME, JOB_ID FROM EMPLOYEES WHERE FIRST_NAME ='david';

SELECT * FROM EMPLOYEES WHERE SALARY >=15000;

-- <> 같지않은
SELECT * FROM EMPLOYEES WHERE DEPARTMENT_ID <> 90;

SELECT * FROM EMPLOYEES WHERE HIRE_DATE = '06/03/07';

-- 문자열 비교, 날짜 대소비교
SELECT * FROM EMPLOYEES WHERE HIRE_DATE >= '06/03/01';

