-- WHERE 조건 및 비교
SELECT * FROM EMPLOYEES;
SELECT * FROM EMPLOYEES WHERE JOB_ID = "IT_PROG";

SELECT FIRST_NAME, JOB_ID FROM EMPLOYEES WHERE FIRST_NAME ='Bruce';

SELECT * FROM EMPLOYEES WHERE SALARY >=15000;

-- <> 같지않은
SELECT * FROM EMPLOYEES WHERE DEPARTMENT_ID <> 90;

SELECT * FROM EMPLOYEES WHERE HIRE_DATE = '06/03/07';

-- 문자열 비교, 날짜 대소비교
SELECT * FROM EMPLOYEES WHERE HIRE_DATE >= '06/03/01';



--BETWEEN ~ AND ~ , 이상 이하 포함
SELECT * FROM EMPLOYEES WHERE SALARY BETWEEN 5000 AND 10000;
SELECT * FROM EMPLOYEES WHERE HIRE_DATE BETWEEN '03/01/01' AND '05/12/13';

--IN 연산자
SELECT * FROM EMPLOYEES WHERE DEPARTMENT_ID IN(50, 60, 70);
SELECT * FROM EMPLOYEES WHERE JOB_ID IN ('IT_PROG', 'ST_MAN');

-- LIKE 연산자, 검색에 사용됨 %와 함께 사용
SELECT * FROM EMPLOYEES WHERE HIRE_DATE LIKE '03%'; --03으로 시작하는
SELECT * FROM EMPLOYEES WHERE HIRE_DATE LIKE '%03'; --03으로 끝나는

SELECT * FROM EMPLOYEES WHERE HIRE_DATE LIKE '%03%'; -- 03이 포함된
SELECT * FROM EMPLOYEES WHERE JOB_ID LIKE '%MAN%';

SELECT * FROM EMPLOYEES WHERE FIRST_NAME LIKE '_a%'; -- 두번쨰 글자가 a인 사람


---
-- NULL 값 찾기
SELECT * FROM EMPLOYEES WHERE COMMISSION_PCT = NULL;
SELECT * FROM EMPLOYEES WHERE COMMISSION_PCT IS NULL; -- 이렇게 찾아야함
SELECT * FROM EMPLOYEES WHERE COMMISSION_PCT IS NOT NULL;

--AND, OR 여기서 AND가 빠름
SELECT * FROM EMPLOYEES WHERE JOB_ID IN ('IT_PROG', 'FI_MGR');
SELECT * FROM EMPLOYEES WHERE JOB_ID = 'IT_PROG' OR JOB_ID = 'FI_MGR';

SELECT * FROM EMPLOYEES WHERE JOB_ID = 'IT_PROG' OR SALARY >= 5000;
SELECT * FROM EMPLOYEES WHERE JOB_ID = 'IT_PROG' AND SALARY >= 5000;

SELECT * FROM EMPLOYEES WHERE JOB_ID = 'IT_PROG' OR JOB_ID = 'FI_MGR' AND SALARY >= 6000; --AND가 먼저 동작
SELECT * FROM EMPLOYEES WHERE (JOB_ID = 'IT_PROG' OR JOB_ID = 'FI_MGR') AND SALARY >= 6000; --OR가 먼저 동작하게 함

-- NOT 부정의 의미
SELECT * FROM EMPLOYEES WHERE DEPARTMENT_ID NOT IN (40,60);
SELECT * FROM EMPLOYEES WHERE JOB_ID NOT LIKE '%MAN%';

-- ORDER BY
SELECT * FROM EMPLOYEES ORDER BY SALARY; -- 기본이 ASCENDING
SELECT * FROM EMPLOYEES ORDER BY DEPARTMENT_ID DESC;

SELECT FIRST_NAME, SALARY * 12 AS 연봉 FROM EMPLOYEES ORDER BY 연봉; --별칭을 ORDER에서 시용힐 수 있음

-- 정령을 2개 이상사용
--  부서번호가 높은 사람들 중에서, 급여가 높은 사람들 기준으로 정렬
SELECT * FROM EMPLOYEES ORDER BY  DEPARTMENT_ID DESC, SALARY DESC; --부서로 처음 정렬하고, 다음으로 샐러리 정렬

-- ORDER BY, ASC, DECS
SELECT * FROM EMPLOYEES WHERE JOB_ID IN ('IT_PROG', 'SA_MAN') ORDER BY FIRST_NAME ASC;