
--DDL , 트랙잭션이 없음
--CREATE, ALTER, DROP

DROP TABLE DEPTS;

CREATE TABLE DEPTS {
    DEPT_NO NUMBER(2), --숫자 2자리
    DEPT_NAME VARCHAR2(30), -- 30바이트, 한글은 15글자, 숫자 영어는 30글자
    DEPT_YN CHAR(1), -- 고정문자 1바이트, 값이 있든 없듣 1바이트
    DEPT_DATE DATE, -- 날짜
    DEPT_BONUS NUMBER(10,2), --정수 10자리와 실수 2자리까지 저장
    DEPT_CONTENT LONG --2기가 가변문자열 (VARCHAR2 보다 더큼)
};

    
SELECT * FROM DEPTS;

INSERT INTO DEPTS VALUES(99, 'HI', 'Y', SYSDATE, 3.14, 'LONG');
INSERT INTO DEPTS VALUES(100, 'HI', 'Y', SYSDATE, 3.14, 'LONG TEXT'); -- DEPT_NO  초과로 100은 수정 안 됨
INSERT INTO DEPTS VALUES(1, 'HI', 'Y', SYSDATE, 3.14, 'LONG');

---------------------
-- 테이블 구조 변경
-- ALTER

DESC DEPTS;
ALTER TABLE DEPTS ADD DEPT_COUNT NUMBER(3); -- NULL값으로 추가됨

SELECT * FROM DEPTS;

ALTER TABLE DEPTS RENAME COLUMN DEPT_COUNT TO EMP_COUNT;

ALTER TABLE DEPTS MODIFY EMP_COUNT NUMBER(5);
ALTER TABLE DEPTS MODIFY EMP_COUNT NUMBER(1);
ALTER TABLE DEPTS MODIFY DEPT_COUNT VARCHAR2(1);

ALTER TABLE DEPTS DROP COLUMN EMP_COUNT;



---------------------
--테이블 삭제
DROP TABLE DEPTS;
DROP TABLE DEPTS CASCADE /*제약조건명*/; -- 테이블의 제약조건을 삭제하면서 테이블 삭제, 위험

DROP TABLE DEPARTMENTS; --DEPARTMENTS는 EMPLOYEES와 참조관계여서 한번에 삭제되지 않음

SELECT * FROM DEPTS;





















