
--숫자 함수

--ROUND 반올림
SELECT ROUND(45.823), ROUND(45.823, 1), ROUND(45.876, 2) FROM DUAL;

--TRUMC, 절삭하는 함수
SELECT TRUNC(45.345), TRUNC(45.345, 0), TRUNC(45.345, 1), TRUNC(45.345, -1) FROM DUAL;

--ABS, 절대값
--CEIL 올림
--FLOOR 내림
SELECT ABS(-123), CEIL(23.3), FLOOR(23.8) FROM DUAL;

--MOD 나머지
SELECT 4/5, MOD(5,3)  FROM DUAL;

---------------------------

--날짜 함수

SELECT SYSDATE FROM DUAL; -- YEAR/ MONTH/ DATE
SELECT SYSTIMESTAMP FROM DUAL; --YEAR/MONTH/DATE HH:MM:SS

--날짜는 연산이 가능
SELECT HIRE_DATE, HIRE_DATE + 1, HIRE_DATE -1 FROM EMPLOYEES;

SELECT FIRST_NAME, SYSDATE - HIRE_DATE FROM EMPLOYEES; -- 일수로 나옴
SELECT FIRST_NAME, (SYSDATE - HIRE_DATE) / 7 FROM EMPLOYEES; -- 몇 주인가
SELECT FIRST_NAME, (SYSDATE - HIRE_DATE) /365 FROM EMPLOYEES; -- 입사 후 몇년이 지났나

-- 날짜의 반올림, 절삭, 잘안씀
SELECT ROUND(SYSDATE), TRUNC(SYSDATE) FROM DUAL; --일자 기준으로 반올림, 절삭
SELECT ROUND(SYSDATE, 'MONTH'), TRUNC(SYSDATE, 'MONTH') FROM DUAL;
SELECT ROUND(SYSDATE, 'YEAR'), TRUNC(SYSDATE, 'YEAR') FROM DUAL;

-- 중요한 변환 함수
-- CHAR >















