-- 문자열 함수
SELECT LOWER('HELLO') AS NAME FROM DUAL; -- 가상테이블, 확인용

-- 소문자, 대문자, 첫 대문자
SELECT LOWER(FIRST_NAME), UPPER(FIRST_NAME), INITCAP(FIRST_NAME) FROM EMPLOYEES;

-- 문자열 길이
SELECT FIRST_NAME, LENGTH(FIRST_NAME) FROM EMPLOYEES;

-- INSTR 문자열 중에 찾기
SELECT FIRST_NAME, INSTR(FIRST_NAME, 'a') FROM EMPLOYEES; -- 없으면 0 리턴

-- SUBSTR 문자열 자르기
SELECT FIRST_NAME, SUBSTR(FIRST_NAME, 3), LAST_NAME ,SUBSTR(LAST_NAME,2, 3) FROM EMPLOYEES; --3미만 자르고 표시하기 , 

-- CONCAT 문자열 합치기
SELECT FIRST_NAME || LAST_NAME, CONCAT(FIRST_NAME,LAST_NAME) FROM EMPLOYEES;

-- LPAD, RPAD 범위 지정 후 특정 문자로 채운다
SELECT LPAD('ABC', 10, '*') FROM DUAL; --LEFT 10칸에 별채움
SELECT LPAD(FIRST_NAME, 10, '*'),RPAD(FIRST_NAME, 10, '*') FROM EMPLOYEES; --RIGHT 10칸에 별

--LTRIM, RTRIM, TRIM
SELECT LTRIM('  HELLO WORLD  '), TRIM('  HELLO WORLD  '), RTRIM('  HELLO WORLD  ') FROM DUAL; --공백삭제
SELECT LTRIM('HELLO WORLD', 'HEL') FROM DUAL; -- 문자 제거로도 쓰임


-- REPLACE
SELECT REPLACE('서울 대구 대전 부산 찍고', ' ', '>' ) FROM DUAL; --공백에 > 넣기
SELECT REPLACE('서울 대구 대전 부산 찍고', ' ', '' ) FROM DUAL; -- 공백에 공백없애기

















