
--DCL
--GRANT, 권한

--유저 목록
SELECT * FROM HR.EMPLOYEES;

SELECT * FROM ALL_USERS;

--유저 권한
SELECT * FROM USER_SYS_PRIVS;

--계정 생성하기, 대문자 추천
CREATE USER USER01 IDENTIFIED BY USER01; --아이디 USER01, 비번 USER01 

--권한 부여하기, 접속 및 생성 등등
GRANT CREATE SESSION, CREATE TABLE, CREATE SEQUENCE, CREATE VIEW, CREATE PROCEDURE TO USER01;
--TABLE SPACE가 지정되야 딴계정에서 데이터 저장가능, USER01에 스패이스 만들기
ALTER USER USER01 DEFAULT TABLESPACE USERS QUOTA UNLIMITED ON USERS;

--권한 회수
REVOKE CREATE SESSION FROM USER01; --접속 권한 없애기

--계정 삭제
DROP USER USER01;

------------------------
--ROLE
CREATE USER USER01 IDENTIFIED BY USER01;

GRANT CONNECT, RESOURCE TO USER01; -- 접속용, 개발용, 관리자용

--테이블 스페이스
ALTER USER USER01 DEFAULT TABLESPACE USERS QUOTA UNLIMITED ON USERS;




--------마우스로 테스만들기
-- USER SQL
ALTER USER "USER02"
DEFAULT TABLESPACE "MYSPACE"
TEMPORARY TABLESPACE "TEMP"
ACCOUNT UNLOCK ;

-- QUOTAS
ALTER USER "USER02" QUOTA UNLIMITED ON "MYSPACE";

-- ROLES
ALTER USER "USER02" DEFAULT ROLE "CONNECT","RESOURCE";

-- SYSTEM PRIVILEGES

DROP USER USER02;












