
--SEQUENCE, 순차적으로 증가하는 값, 중요
--PK에도 적용할 수 있음

SELECT * FROM USER_SEQUENCES;

--시퀀스 생성
CREATE SEQUENCE DEPTS_SEQ
    INCREMENT BY 1
    START WITH 1
    MAXVALUE 10
    NOCACHE --캐시에 시퀀스를 두지 않음
    NOCYCLE; -- 최대값에 도달하면 재사용하지 않음


--사용
DROP TABLE DEPTS;

CREATE TABLE DEPTS(
    DEPT_NO NUMBER(300) PRIMARY KEY,
    DEPT_NAME VARCHAR(30)
);

SELECT * FROM DEPTS;

--시퀀스 사용방법 
SELECT DEPTS_SEQ.CURRVAL FROM DUAL; --현재 시퀀스
SELECT DEPTS_SEQ.NEXTVAL FROM DUAL; --현재 시퀀스 증가값만큼 증가

--시퀀스 적용하기
INSERT INTO DEPTS VALUES( DEPTS.NEXTVAL, 'EXAMPLE'); 

SELECT * FROM DUAL;
SELECT * FROM DEPTS;

--시퀀스 수정
ALTER SEQUENCE DEPTS_SEQ MAXVALUE 1000; --최대값 수정
ALTER SEQUENCE DEPTS_SEQ INCREMENT BY 10; --증가값 수정

SELECT * FROM DEPTS;
ROLLBACK;

--1. 시퀀스 값 증가값을 음수로
SELECT DEPTS_SEQ.CURRVAL FROM DUAL; --현재 값 확인하기
ALTER SEQUENCE DEPTS_SEQ INCREMENT BY -30;
ALTER SEQUENCE DEPTS_SEQ INCREMENT BY 10;

--2. 시퀀스 값을 전진
SELECT DEPTS_SEQ.NEXTVAL FROM DUAL;
--3. 다시 증가값을 1로 변경
ALTER SEQUENCE DEPTS_SEQ INCREMENT BY 1;

----------
--시퀀스 응용, 데이터가 많을때, 알아두기만
--문자열 PK (년도값-일련번호)

CREATE TABLE DEPTS2(
    DPRT_NO VARCHAR2(20) PRIMARY KEY,
    LEFT_NAME VARCHAR2(30)
);

INSERT INTO DEPTS2 VALUES(TO_CHAR(SYSDATE, 'YYYY-MM-') || LPAD(DEPTS_SEQ.NEXTVAL, 6, 0), 'SAMPLE');

SELECT * FROM DEPTS2;


--삭제
DROP SEQUENCE 시퀀스명;














