
-- 논리적 데이터 모델링에서 내보내기
-- https://www.erdcloud.com/d/beWLGWcGwJb6uizt9



CREATE TABLE "멤버" (
	"ID"	VARCHAR2(30)		NOT NULL,
	"NAME"	VARCHAR2(30)		NULL,
	"ADDRESS"	VARCHAR2(30)		NULL
);

CREATE TABLE "Untitled" (
	"NUM"	NUMBER(10)		NOT NULL,
	"TITLE"	VARCHAR2(30)		NULL,
	"CONTENT"	VARCHAR2(30)		NULL,
	"ID"	VARCHAR2(30)		NOT NULL
);

CREATE TABLE "CopyOfUntitled" (
	"NUM"	NUMBER(10)		NOT NULL,
	"TITLE"	VARCHAR2(100)		NULL,
	"CONTENT"	VARCHAR2(500)		NULL,
	"ID"	VARCHAR2(30)		NOT NULL,
	"NUM2"	NUMBER(10)		NOT NULL
);

CREATE TABLE "ADMIN" (
	"ID"	VARCHAR2(30)		NOT NULL,
	"REGDATE"	DATE		NULL,
	"Field"	VARCHAR(255)		NULL
);

CREATE TABLE "CopyOfADMIN" (
	"ID"	DATE		NULL,
	"Field"	VARCHAR(255)		NULL
);

CREATE TABLE "COLUMN" (
	"CMD"	NUMBER(10)		NOT NULL,
	"TITLE"	VARCHAR2(30)		NULL,
	"CNAME"	VARCHAR2(50)		NULL,
	"Field"	VARCHAR(255)		NULL
);

CREATE TABLE "COLUMN_LIST" (
	"CMD"	NUMBER(10)		NOT NULL,
	"ID"	VARCHAR2(30)		NOT NULL
);

ALTER TABLE "멤버" ADD CONSTRAINT "PK_멤버" PRIMARY KEY (
	"ID"
);

ALTER TABLE "Untitled" ADD CONSTRAINT "PK_UNTITLED" PRIMARY KEY (
	"NUM"
);

ALTER TABLE "CopyOfUntitled" ADD CONSTRAINT "PK_COPYOFUNTITLED" PRIMARY KEY (
	"NUM"
);

ALTER TABLE "ADMIN" ADD CONSTRAINT "PK_ADMIN" PRIMARY KEY (
	"ID"
);

ALTER TABLE "COLUMN" ADD CONSTRAINT "PK_COLUMN" PRIMARY KEY (
	"CMD"
);

ALTER TABLE "COLUMN_LIST" ADD CONSTRAINT "PK_COLUMN_LIST" PRIMARY KEY (
	"CMD",
	"ID"
);

ALTER TABLE "ADMIN" ADD CONSTRAINT "FK_멤버_TO_ADMIN_1" FOREIGN KEY (
	"ID"
)
REFERENCES "멤버" (
	"ID"
);

ALTER TABLE "COLUMN_LIST" ADD CONSTRAINT "FK_COLUMN_TO_COLUMN_LIST_1" FOREIGN KEY (
	"CMD"
)
REFERENCES "COLUMN" (
	"CMD"
);

ALTER TABLE "COLUMN_LIST" ADD CONSTRAINT "FK_멤버_TO_COLUMN_LIST_1" FOREIGN KEY (
	"ID"
)
REFERENCES "멤버" (
	"ID"
);

